version: "3.8"

services:
  api:
    container_name: mapbox-demo-api
    restart: unless-stopped
    image: nategage/mapbox-demo-api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3300:3300" 

  client:
    container_name: mapbox-demo-client
    restart: unless-stopped
    image: nategage/mapbox-demo-client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
